// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var PL_data = require("./pL_data.js");

function makeSilent() {
  PL_data.nand[/* isSilent */3] = /* false */0;
  return /* () */0;
}

function makePP() {
  PL_data.nand[/* execute */0] = PL_data.NANDPP[/* execute */0];
  PL_data.nand[/* addSS */1] = PL_data.NANDPP_SS[/* addSS */0];
  return /* () */0;
}

function makeGG() {
  PL_data.nand[/* execute */0] = PL_data.NANDGG[/* execute */0];
  PL_data.nand[/* addSS */1] = PL_data.NANDGG_SS[/* addSS */0];
  return /* () */0;
}

function turnSSOn() {
  PL_data.nand[/* ssSwitch */2] = /* true */1;
  return /* () */0;
}

function makeDry() {
  PL_data.nand[/* dryRun */4] = /* true */1;
  return /* () */0;
}

var flags_000 = /* tuple */[
  "-s",
  makeSilent
];

var flags_001 = /* :: */[
  /* tuple */[
    "-pp",
    makePP
  ],
  /* :: */[
    /* tuple */[
      "-ll",
      makeGG
    ],
    /* :: */[
      /* tuple */[
        "-addSS",
        turnSSOn
      ],
      /* :: */[
        /* tuple */[
          "-dry",
          makeDry
        ],
        /* [] */0
      ]
    ]
  ]
];

var flags = /* :: */[
  flags_000,
  flags_001
];

exports.makeSilent = makeSilent;
exports.makePP     = makePP;
exports.makeGG     = makeGG;
exports.turnSSOn   = turnSSOn;
exports.makeDry    = makeDry;
exports.flags      = flags;
/* PL_data Not a pure module */
