// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var PL_data = require("./pL_data.js");

function setLanguage(language) {

    var lower = language.toLowerCase();
    if (lower === 'nand') {
        PL_data.nand[/* execute */0] = PL_data.NAND[/* execute */0];
        PL_data.nand[/* addSS */1] = PL_data.NAND_SS[/* addSS */0];
    } else if (lower === 'nandpp') {
        PL_data.nand[/* execute */0] = PL_data.NANDPP[/* execute */0];
        PL_data.nand[/* addSS */1] = PL_data.NANDPP_SS[/* addSS */0];
    } else if (lower === 'nandgg') {
        PL_data.nand[/* execute */0] = PL_data.NANDGG[/* execute */0];
        PL_data.nand[/* addSS */1] = PL_data.NANDGG_SS[/* addSS */0];
    } else {
        throw 'Invalid language';
    }
}

function setSS(val) {
    PL_data.nand[/* ssSwitch */2] = val;
}

function setDry(val) {
    PL_data.nand[/* dryRun */4] = val;
}

exports.setDry = setDry;
exports.setSS = setSS;
exports.setLanguage = setLanguage;

/* PL_data Not a pure module */
