// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var SS         = require("./sS.js");
var PL_functor = require("./pL_functor.js");
var PL_modules = require("./pL_modules.js");

var NAND = PL_functor.PLFromBackEnd(PL_modules.NAND_back_end);

var NAND_SS = SS.SSFromBackEnd(PL_modules.NAND_back_end);

var NANDPP = PL_functor.PLFromBackEnd(PL_modules.NANDPP_back_end);

var NANDPP_SS = SS.SSFromBackEnd(PL_modules.NAND_back_end);

var NANDGG = PL_functor.PLFromBackEnd(PL_modules.NANDGG_back_end);

var NANDGG_SS = SS.SSFromBackEnd(PL_modules.NANDGG_back_end);

var nand = /* record */[
  /* execute */NAND[/* execute */0],
  /* addSS */NAND_SS[/* addSS */0],
  /* ssSwitch : false */0,
  /* isSilent : false */0,
  /* dryRun : false */0
];

exports.NAND      = NAND;
exports.NAND_SS   = NAND_SS;
exports.NANDPP    = NANDPP;
exports.NANDPP_SS = NANDPP_SS;
exports.NANDGG    = NANDGG;
exports.NANDGG_SS = NANDGG_SS;
exports.nand      = nand;
/* NAND Not a pure module */
