// Generated by BUCKLESCRIPT VERSION 1.9.0, PLEASE EDIT WITH CARE
'use strict';

var PL_functor      = require("./pL_functor.js");
var Caml_exceptions = require("bs-platform/lib/js/caml_exceptions.js");

var Invalid_index = Caml_exceptions.create("PL_modules.NAND_back_end.Invalid_index");

function evalIndex(_, ind) {
  if (ind) {
    return ind[0];
  } else {
    throw Invalid_index;
  }
}

function supportsBinop(b) {
  return +(b === "NAND");
}

var NAND_back_end = /* module */[
  /* evalIndex */evalIndex,
  /* supportsBinop */supportsBinop,
  /* supportsLoop : false */0,
  /* supportsI : false */0,
  /* supportsAsg : false */0,
  /* muxDefStr */"def a := MUX(b, c, d) { \n         nb := b NAND b\n         u := c NAND nb \n         v := d NAND b \n         a := u NAND v \n       }"
];

function evalIndex$1(st, ind) {
  if (ind) {
    return ind[0];
  } else {
    return PL_functor.safeFind("i", st);
  }
}

function supportsBinop$1(b) {
  return +(b === "NAND");
}

var NANDPP_back_end = /* module */[
  /* evalIndex */evalIndex$1,
  /* supportsBinop */supportsBinop$1,
  /* supportsLoop : true */1,
  /* supportsI : true */1,
  /* supportsAsg : false */0,
  /* muxDefStr */"def a := MUX(b, c, d) { \n         nb := b NAND b\n         u := c NAND nb \n         v := d NAND b \n         a := u NAND v \n       }"
];

function evalIndex$2(st, ind) {
  if (ind) {
    return ind[0];
  } else {
    return PL_functor.safeFind("i", st);
  }
}

function supportsBinop$2() {
  return /* true */1;
}

var NANDGG_back_end = /* module */[
  /* evalIndex */evalIndex$2,
  /* supportsBinop */supportsBinop$2,
  /* supportsLoop : true */1,
  /* supportsI : true */1,
  /* supportsAsg : true */1,
  /* muxDefStr */"def a := MUX(b, c, d) { \n         tmp_0 := c \n         tmp_1 := d\n         temp_0 := i \n         i := b \n         res := tmp_i \n         i := temp_0 \n         a := res  \n       }"
];

exports.NAND_back_end   = NAND_back_end;
exports.NANDPP_back_end = NANDPP_back_end;
exports.NANDGG_back_end = NANDGG_back_end;
/* PL_functor Not a pure module */
